#!/usr/bin/env bash
# chrome-profile-setup.sh — Create an isolated Chrome profile for dev automation.
#
# Usage:
#   pnpm dev:browser:setup                              # defaults: chrome-myapp, port 19222
#   pnpm dev:browser:setup -- myprofile 19223            # → chrome-myprofile on port 19223
#   bash tools/dev/chrome-profile-setup.sh [name] [port]
#
# Arguments (both optional):
#   name   Short profile name, auto-prefixed with "chrome-" (default: myapp)
#   port   CDP remote debugging port (default: 19222)
#
# What it does:
#   1. Creates an isolated Chrome data directory (~/.chrome-profiles/<name>)
#   2. Generates a launcher script (~/.local/bin/<name>)
#   3. Writes CHROME_PROFILE and CHROME_CDP_PORT to .env (idempotent)
#
# Idempotent: safe to run multiple times. Re-creates the launcher script and
# upserts env vars in .env without duplicating lines.
#
# Requires: bash, Google Chrome installed
# Context:  One-time setup per developer machine, re-run to change profile/port.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

# ── Defaults & arguments ────────────────────────────────────────────────────

# Skip "--" if pnpm forwards it as first arg
[[ "${1:-}" == "--" ]] && shift

SHORT_NAME="${1:-myapp}"
SHORT_NAME="${SHORT_NAME#--}" # strip leading -- (pnpm --name)
SHORT_NAME="${SHORT_NAME#-}"  # strip leading -
PROFILE_NAME="chrome-${SHORT_NAME}"
CDP_PORT="${2:-19222}"

if ! [[ "$CDP_PORT" =~ ^[0-9]+$ ]] || ((CDP_PORT < 1024 || CDP_PORT > 65535)); then
  echo "ERROR: Port must be a number between 1024 and 65535." >&2
  exit 1
fi

# ── Detect Chrome binary ────────────────────────────────────────────────────

if [[ -n "${CHROME_BIN:-}" ]] && [[ -x "$CHROME_BIN" ]]; then
  : # use provided CHROME_BIN
elif [[ "$(uname)" == "Darwin" ]]; then
  CHROME_BIN="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
else
  CHROME_BIN="$(command -v google-chrome || command -v google-chrome-stable || echo "")"
fi

if [[ -z "$CHROME_BIN" ]] || [[ ! -x "$CHROME_BIN" ]]; then
  echo "ERROR: Google Chrome not found." >&2
  echo "Install Chrome or set CHROME_BIN environment variable." >&2
  exit 1
fi

PROFILES_DIR="$HOME/.chrome-profiles"
SCRIPTS_DIR="$HOME/.local/bin"

# ── Create profile directory ─────────────────────────────────────────────────

PROFILE_DIR="$PROFILES_DIR/$PROFILE_NAME"
mkdir -p "$PROFILE_DIR"
echo "  ✓ Profile directory: $PROFILE_DIR"

# ── Generate launcher script ─────────────────────────────────────────────────

mkdir -p "$SCRIPTS_DIR"
LAUNCHER="$SCRIPTS_DIR/$PROFILE_NAME"

cat >"$LAUNCHER" <<LAUNCHER_EOF
#!/usr/bin/env bash
# Launch Chrome with isolated profile: $PROFILE_NAME
# CDP port: $CDP_PORT (for Playwright/Puppeteer/MCP)
# Generated by: tools/dev/chrome-profile-setup.sh

# Kill previous instance on this port if any
lsof -ti tcp:$CDP_PORT | xargs kill -9 2>/dev/null || true
sleep 0.5

exec "$CHROME_BIN" \\
  --user-data-dir="$PROFILE_DIR" \\
  --remote-debugging-port=$CDP_PORT \\
  --remote-debugging-address=127.0.0.1 \\
  --no-first-run \\
  --no-default-browser-check \\
  --disable-features=ChromeWhatsNewUI \\
  "\$@" 2>/dev/null
LAUNCHER_EOF

chmod +x "$LAUNCHER"
echo "  ✓ Launcher script: $LAUNCHER"

# ── Upsert .env ──────────────────────────────────────────────────────────────

_upsert_env() {
  local key="$1" value="$2" file="$PROJECT_DIR/.env"

  # Create .env from .env.example if it doesn't exist
  if [[ ! -f "$file" ]]; then
    if [[ -f "$PROJECT_DIR/.env.example" ]]; then
      cp "$PROJECT_DIR/.env.example" "$file"
    else
      touch "$file"
    fi
  fi

  if grep -qE "^${key}=" "$file" 2>/dev/null; then
    # Replace existing value (portable sed -i)
    local tmp
    tmp=$(mktemp)
    sed "s|^${key}=.*|${key}=${value}|" "$file" >"$tmp"
    mv "$tmp" "$file"
    echo "  ↺ .env: ${key}=${value} (updated)"
  else
    echo "${key}=${value}" >>"$file"
    echo "  ✓ .env: ${key}=${value} (added)"
  fi
}

_upsert_env CHROME_PROFILE "$PROFILE_NAME"
_upsert_env CHROME_CDP_PORT "$CDP_PORT"

# ── Verify PATH ──────────────────────────────────────────────────────────────

if ! echo "$PATH" | tr ':' '\n' | grep -qx "$SCRIPTS_DIR"; then
  echo ""
  echo "  ⚠  $SCRIPTS_DIR is not in your PATH."
  echo "     Add to your shell rc:"
  echo "       export PATH=\"\$HOME/.local/bin:\$PATH\""
fi

# ── Summary ──────────────────────────────────────────────────────────────────

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Setup complete"
echo ""
echo "Launch Chrome:  $PROFILE_NAME"
echo "Open with devs: pnpm dev:browser"
echo "CDP URL:        http://localhost:$CDP_PORT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
